name: bmi_calc
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:

    sdk: flutter
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  firebase_auth: ^3.3.10
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.10
  dio: ^4.0.4  # http request
  http: ^0.13.4
  url_launcher: ^6.0.20
  bottom_navy_bar: ^6.0.0 # bottom navigation bar
  gender_picker: ^1.1.0 # genders
  translator: ^0.1.7 #translator
  sqflite: ^2.0.2+1 #database storage
  uuid: ^3.0.6
  google_fonts: ^2.3.2
  hexcolor: ^2.0.7
  fl_chart: ^0.51.0 #animations
  google_mobile_ads: ^1.2.0 #admob

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/


